### PR TITLE
Fixes #221 and #222 - fixes GraphQLCache file globbing

### LINKED ISSUE #221: Initial fragment caching does not work for some glob patterns
If `.graphqlconfig` contains an `includes` key, with only a single glob such as below, the resulting set of matched files will always be empty.

```json
{
  "includes": [ "{path/to}/**/*.{js, graphql}" ]
}
```

In the above example, glob would ultimately look for files ending in `.js` or `.graphql` which are literally in a directory called `{path/to}`. 

This occurs because the underlying library performing the globbing (minimatch), does not expand glob braces when there's only a single value inside those braces. For instance, some implementations of glob (such as your shell) expand `{foo}` into `foo`. Minimatch does not perform an expansion in this case. It's unclear if this is by design or not. 

When `includes` contains multiple glob paths, this behavior does not occur because, as one would expect, minimatch correctly expands `{path/a,path/b}/**/*.{js, graphql}` into `['path/a/**.{js, graphql}', 'path/a/**.{js, graphql}']`.

The end result is that fragments are not cached when graphql-language-service first loads in the above case. Caching is thus delayed until each file has changed (a fact which is learned only after being notified by watchman or via [language service protocol](https://langserver.org/)).

### PR DESCRIPTION
**Pull request by mgadda**
See detailed descriptions of issues in #221 and #222.

### CODE REVIEW

File: packages/server/src/GraphQLCache.js [hunk 1]
```diff
@@ -246,9 +242,15 @@ export class GraphQLCache implements GraphQLCacheInterface {
     rootDir: string,
     includes: string[],
   ): Promise<Array<GraphQLFileMetadata>> => {
+    let pattern: string;
+    if (includes.length === 1) {
```
Comment (lostplan) [inline packages/server/src/GraphQLCache.js]: Nit: add link to issue

**Comment by mgadda** [comment]
It could be challenging since glob is hitting the file system.

File: packages/server/src/GraphQLCache.js (hunk 1 above)
Comment (mgadda) [reply packages/server/src/GraphQLCache.js]: I don't think it's a bug. It sort of depends on which implementation of globs you look at. Some of them (fish shell) expanded `a{p}e` into `ape` and others (bash, sh, minimatch) leave `a{p}e` as is. My guess is that minimatch is modeled after bash and filing a ticket will be fruitless.

Comment (lostplan) [reply packages/server/src/GraphQLCache.js]: I just mean we should add a note-to-self about why `length ===1` is special cased (i.e. a link to #222). To prevent future engineers from cleaning up this code.

Comment (mgadda) [reply packages/server/src/GraphQLCache.js]: Ah, no problem. I'll update the PR with a comment.
